### ISSUE TITLE
Bleadperl 5.39.1 breaks Slick-0.004

### ISSUE THREAD

**Issue by andk** [rawleyfowler/Slick#1]
X-Ref: https://github.com/Perl/perl5/issues/21269

**Comment by rawleyfowler** [comment]
Is that likely to be reverted? It seems like this is a fairly large issue. If not what is the approach to fixing this? I'm assuming this is breaking due to a dependency rather than Slick itself.

**Comment by rawleyfowler** [comment]
@andk Just pushed `0.006`, I will close this if it passes on `5.39.1` via any CPAN-tester.

**Comment by rawleyfowler** [comment]
Fixed in **0.006**
